version: '3.8'
services:
  plumber:
    image: registry.gitlab.com/petarstf/cc_default
    volumes:
      - ./:/code
    restart: always
  nginx:
    image: nginx
    ports:
      - '8881:8881'
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - plumber