version: '3.8'
services:
  plumber:
    image: registry.gitlab.com/petarstf/cc_default
    volumes:
      - ./:/cc_default
    restart: always
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - plumber
  # lb:
  #   image: 'dockercloud/haproxy'
  #   links:
  #    - plumber
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - '80:80'
  #   restart: always