FROM rocker/r-ver:4.0.2

# Update linux libs

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libxml2 \
    libpq-dev

# Set working dir

RUN mkdir /code

WORKDIR /code

# Install R Packages


RUN R -e "install.packages(c('XML', 'xml2', 'devtools'), dependencies = T)"

RUN R -e "devtools::install_version('janitor', version = '2.0.1', dependencies = T)"

RUN R -e "devtools::install_url('https://github.com/microsoft/LightGBM/releases/download/v3.0.0/lightgbm-3.0.0-r-cran.tar.gz')"

RUN R -e "devtools::install_version('tidyverse', version = '1.3.0', dependencies = T)"

RUN R -e "devtools::install_version('tidymodels', version = '0.1.1', dependencies = T)"

RUN R -e "devtools::install_version('plumber', version = '1.0.0', dependencies = T)"

RUN R -e "devtools::install_version('DBI', version = '1.1.0', dependencies = T)"

RUN R -e "devtools::install_version('RPostgres', version = '1.2.1', dependencies = T)"

RUN R -e "devtools::install_version('jsonlite', version = '1.7.0', dependencies = T)"

# COPY necessary files

COPY ./05_saved_models/lightgbm_model ./05_saved_models/lightgbm_model
COPY ./08_api/plumber.R .
COPY ./08_api/predict_db.R ./08_api/predict_db.R

# Expose on port

EXPOSE 8000

# Command that runs the container as an executable 

ENTRYPOINT ["R", "-f", "./08_api/plumber.R", "--slave"]