version: '3.8'
services:
  plumber:
    image: test
    volumes:
      - ./:/code
    restart: always
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - plumber