version: '3.8'
services:
  plumber:
    image: ccdefault
    restart: always
  lb:
    image: 'dockercloud/haproxy'
    links:
     - plumber
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
    restart: always